### ISSUE TITLE
Error: Cannot find module '../config' ?

### ISSUE THREAD

**Issue by mw66** [postor/react-wechat-provider#1]
Hi,

followed your steps in readme:

yarn dev
then visit http://localhost:3000

but it errors out:

```
{ Error: Cannot find module '../config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home//project/unzip/example/pages/index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module._compile (/home//project/unzip/example/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at _callee$ (/home//project/unzip/example/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/home//project/unzip/example/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home//project/unzip/example/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home//project/unzip/example/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home//project/unzip/example/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home//project/unzip/example/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13 code: 'MODULE_NOT_FOUND' }
```

what I should check?

**Comment by postor** [comment]
it requires the appid and secret config for wechat app, you can get them from wechat app admin page https://open.weixin.qq.com

```
mv config-example.json config.json
# fill your wechat appid secret .etc | 填写微信appid secret等
vi config.json
```
refer https://github.com/postor/react-wechat-provider#run-example
